centilgroup/rails-react-boilerplate

front/js/components/Main/Main.js
front/js/components/ProjectDropDown/ProjectDropDown.js
front/js/components/Settings/Settings.js

Team, this PR includes the skeleton for the following three Components:
- Settings
- ProjectDrop
- Main
I created Directories for each Component and touched .js files for each then laid out the bones of the Component within the associated .js file.
I look forward to your review. Please let me know if and when merged.

Settings projectdrop main components

---

front/js/components/FlowDetails/FlowDetails.js
front/js/components/Preview/Preview.js

This PR includes the skeleton for the following Components:
- FlowDetails
- Preview
Each have their own directories and .js files.

Flowdetails preview

---

front/js/components/App/App.js
front/js/components/Login/Login.js
front/js/components/Main/Main.js
front/js/components/app.js
package-lock.json
package.json

This pull request installed react-router-dom, sets up the Routes within the App component, begins flushing out the functionality of the login and demonstrates within the Main that the login occurred successfully.
Once merged everyone will need to install the new dependencies locally.

Login and router

---

front/js/components/App/App.js
front/js/components/Dashboard/Dashboard.js
front/js/components/Data.js
front/js/components/Main/Main.js
front/js/components/Nav/Nav.js
front/js/components/Preview/Preview.js
front/js/components/ProjectDropDown/ProjectDropDown.js
front/js/components/ProjectSelector/ProjectSelector.js
package-lock.json
package.json

This pull request integrates:
- Chart.js chart package selected by Mia (with this new package installation once this PR is merged and pulled down to Master we will all need to install by running `npm i`
- ProjectSelector functionality
- ProjectDropDown functionality
- Routing related to displaying the two Dashboards
- Passing relevant Project Data into selected project Dashboard
- Setting state in Main with project1name, project2name, project1data, and project2data
- Prettier file cleanup
Thank you in advance for the review. This should get us to an even better place in terms of our Dashboard and charts display.

Project selector

---

app/assets/stylesheets/scaffolds.scss
front/js/components/Dashboard/Dashboard.js
front/js/components/Preview/Preview.js

Good morning, all.
This PR integrates our first chart.js for the Flow Load. We can discuss in more detail during our Pairing this morning. 
We will likely have some merge conflicts but we can sort through as a team.
Thanks!

Preview load

---

app/controllers/jiras_controller.rb
app/services/jira_manager.rb
app/views/jiras/index.json.jbuilder
front/css/base/base.scss
front/js/components/App/App.js
front/js/components/Dashboard/Dashboard.js
package-lock.json
package.json

- Pagination with infinite-scroll
- Navbar with profile and logout buttons

Jira activity pagination

---

app/controllers/jiras_controller.rb
app/models/issue.rb
app/models/project.rb
app/models/user.rb
app/services/jira_manager.rb
db/migrate/20210120085958_create_projects.rb
db/migrate/20210120115322_create_issues.rb
db/schema.rb
front/css/base/base.scss
front/js/components/Dashboard/Dashboard.js
lib/tasks/sync_jira.rake
test/fixtures/issues.yml
test/fixtures/projects.yml
test/models/issue_test.rb
test/models/project_test.rb

This will sync the Jira projects and issues for the dashboard calculations.

Rake task to sync jira projects and issues

---

front/css/base/base.scss
front/css/base/typography.scss
front/js/components/Dashboard/Dashboard.js

Focus and Commit risk breakdown implementation

---

front/css/base/base.scss
front/css/base/typography.scss
front/js/components/Dashboard/Dashboard.js
front/js/components/Profile/Profile.js

Dashboard and Profile improvements

---

front/js/components/Dashboard/Dashboard.js
front/js/components/Login/Login.js
front/js/components/Login/OneTimePassword.js
front/js/components/Password/Password.js
front/js/components/Password/PasswordEdit.js
front/js/components/Profile/Profile.js
front/js/components/Register/Register.js

Footer addition

---

app/assets/stylesheets/app.scss
app/controllers/jiras_controller.rb
app/services/jira_manager.rb
app/views/jiras/index.json.jbuilder
app/views/jiras/stat.json.jbuilder
db/migrate/20210202140217_add_issue_type_to_issue.rb
db/migrate/20210202170059_add_columns_to_issue.rb
db/schema.rb
front/css/app.scss
front/css/base/base.scss
front/js/components/Dashboard/Dashboard.js

Focus section

---

app/controllers/jiras_controller.rb
app/services/jira_manager.rb
app/views/jiras/stat.json.jbuilder
front/js/components/Dashboard/Dashboard.js

Projects filter implementation

---

front/js/components/Profile/Profile.js

Profile page update.

---

front/js/components/Dashboard/Dashboard.js

This solves unnecessary loading skeleton display.

Skeleton loading handling during request failure and success

---

app/controllers/users/sessions_controller.rb
app/views/users/sessions/sync_projects.json.jbuilder
config/routes.rb
front/js/components/Dashboard/Dashboard.js

Sync button display for projects and issues

---

app/controllers/jiras_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/sessions_controller.rb
app/views/jiras/stat.json.jbuilder
config/routes.rb
db/migrate/20210318060141_add_min_max_config_to_user.rb
db/migrate/20210319071001_add_sortable_items_to_user.rb
db/schema.rb
front/js/components/Dashboard/Dashboard.js
package-lock.json
package.json

MinMax & Sortable section features

---

app/assets/stylesheets/app.scss
front/js/components/Dashboard/Dashboard.js
front/js/components/Profile/Profile.js

[FLOW-28] Header design change.

---

app/controllers/jiras_controller.rb
app/services/jira_manager.rb
app/views/jiras/stat.json.jbuilder
db/migrate/20210406163457_change_default_value_for_two_factor_auth_to_user.rb
db/schema.rb
front/js/components/Dashboard/Dashboard.js

Condensed VPI by project implementation.

---

Gemfile
Gemfile.lock
app/controllers/jiras_controller.rb
app/controllers/users/sessions_controller.rb
app/services/jira_manager.rb
app/views/jiras/stat.json.jbuilder
app/views/users/sessions/create.json.jbuilder
app/views/users/sessions/pre_otp.json.jbuilder
app/views/users/sessions/profile.json.jbuilder
db/migrate/20210412054647_add_initial_config_to_user.rb
db/migrate/20210415081806_add_status_transitions_to_issue.rb
db/migrate/20210415123537_change_values_for_min_max_and_sortable_items_to_user.rb
db/schema.rb
front/js/components/App/App.js
front/js/components/Dashboard/Dashboard.js
front/js/components/Login/Login.js
front/js/components/Login/OneTimePassword.js
front/js/components/Password/Password.js
front/js/components/Password/PasswordEdit.js
front/js/components/Profile/Profile.js
front/js/components/Register/Register.js
front/js/components/Settings/LinkJira.js
front/js/components/Settings/SyncIssues.js
front/js/components/Settings/SyncProjects.js
front/js/components/Shared/Footer.js

[FLOW-59] Configuration wizard implementation.

---

app/controllers/users/sessions_controller.rb
app/services/jira_manager.rb
app/views/jiras/index.json.jbuilder
config/routes.rb
front/js/components/Dashboard/Dashboard.js

Projects, Issues & Boards CSV Ingest.

---

app/controllers/users/sessions_controller.rb
app/models/user.rb
config/routes.rb
front/js/components/Login/Login.js
front/js/components/Profile/Profile.js
front/js/components/Settings/ProfileSection.js

[FLOW-78] Username bug fix and improvements.

---

front/js/components/Dashboard/WIP.js

[FLOW-75] Running WIP - MVP#2

---

app/controllers/dashboard_controller.rb
app/controllers/users/sessions_controller.rb
app/models/board.rb
app/models/dora_metric.rb
app/services/dashboard_manager.rb
app/views/dashboard/dora_metrics.json.jbuilder
app/views/users/sessions/create.json.jbuilder
app/views/users/sessions/pre_otp.json.jbuilder
app/views/users/sessions/profile.json.jbuilder
app/views/users/sessions/update.json.jbuilder
config/routes.rb
db/migrate/20210614041141_create_dora_metrics.rb
db/migrate/20210615054848_add_dora_to_user.rb
db/schema.rb
front/js/components/Dashboard/DORA.js
front/js/components/Dashboard/Dashboard.js
lib/tasks/dora_metrics.rake
test/fixtures/dora_metrics.yml
test/models/dora_metric_test.rb

[FLOW-91] DORA Metrics MVP#1 done & [FLOW-92] DORA Metrics MVP#2 partially done

---

app/controllers/dashboard_controller.rb
app/controllers/users/sessions_controller.rb
app/services/dashboard_manager.rb
app/services/jira_manager.rb
app/views/dashboard/dora_metrics.json.jbuilder
db/migrate/20210702060510_add_sprints_to_board.rb
db/schema.rb
front/js/components/Dashboard/DORA.js

Snap to sprints filter
